name: Ubuntu basic build-and-test

on:
  # Allow manual triggering
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Install packages
      run: >-
        sudo apt-get update &&
        sudo apt-get install -y
        guile-3.0-dev
        libfreetype-dev
        libmpg123-dev
        libopenal-dev
        libreadline-dev
        libvorbis-dev
        libsdl2-dev
        libsdl2-image-dev
        libsdl2-mixer-dev
        libsdl2-ttf-dev
        libturbojpeg0-dev
    - name: Cache tarballs
      id: cache-tarballs
      uses: actions/cache@v3
      with:
        path: |
          guile-sdl2-0.8.0.tar.gz
          guile-opengl-0.2.0.tar.gz
          chickadee-0.10.0.tar.gz
        key: source-tarballs
    - name: Download tarballs
      if: steps.cache-tarballs.outputs.cache-hit !=  'true'
      run: |
        wget https://files.dthompson.us/guile-sdl2/guile-sdl2-0.8.0.tar.gz
        wget https://ftp.gnu.org/gnu/guile-opengl/guile-opengl-0.2.0.tar.gz
        wget https://files.dthompson.us/chickadee/chickadee-0.10.0.tar.gz
    - name: add env vars for app directory
      run: |
        echo "GUILE_LOAD_PATH=`pwd`/app/share/guile/site/3.0" >> $GITHUB_ENV
        echo "GUILE_LOAD_COMPILED_PATH=`pwd`/app/lib/guile/3.0/site-ccache" >> $GITHUB_ENV
    - name: build guile-sdl2
      run: |
        tar xzvf guile-sdl2-0.8.0.tar.gz
        cd guile-sdl2-0.8.0
        ./configure --prefix=`pwd`/../app
        make
        make install
    - name: build guile-opengl
      run: |
        tar xzvf guile-opengl-0.2.0.tar.gz
        cd guile-opengl-0.2.0
        ./configure --prefix=`pwd`/../app
        make
        make install
    - name: build chickadee
      run: |
        tar xzvf chickadee-0.10.0.tar.gz
        cd chickadee-0.10.0
        ./configure --prefix=`pwd`/../app
        make
        make install
    - run: ls -lR
  
    
  

          
   
