name: Ubuntu basic build-and-test

on:
  # Allow manual triggering
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Install packages
      run: >-
        sudo apt-get update &&
        sudo apt-get install -y
        guile-3.0
   
